name: sphinx-docs

on: [push]

jobs:
  build-docs:
    strategy:
      matrix:
        os: [ubuntu-latest]
        include:
          - os: ubuntu-latest
            command: conda env create --name snowfake python=3.9
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repo content
        uses: actions/checkout@v2
      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install snowfake dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install sphinx myst-parser matplotlib tqdm scipy numpy
          python -m pip install snowfake
      
      - name: Build html docs
        run: |
          make html
