name: sphinx-docs

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-docs:
    
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10"]
    
    steps:
      - name: Checkout repo content
        uses: actions/checkout@v2
      - name: Set up python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install sphinx myst-parser matplotlib tqdm scipy numpy
          python -m pip install sphinx-rtd-theme
          python -m pip install snowfake
      - name: Build html docs
        run: |
          cd docs
          make clear
          make html
