name: sphinx-docs

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-docs:
    
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo content
      uses: actions/checkout@v1
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --use-feature=in-tree-build .[docs]  # Install with docs option
    # Standard drop-in approach that should work for most people.
    - name: Update Sphinx docs
      uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "docs/"
    
    # Create an artifact of the html output.
    #- name: create output of artifact
    #  uses: actions/upload-artifact@v2
    #  #with:
    #  name: DocumentationHTML
    #  path: docs/docs/html/
      
      
    - name: Commit documentation changes
      run: |
        git clone https://github.com/EvanBianco/snowfake.git --branch gh-pages --single-branch gh-pages
        mkdir gh-pages/docs
        cp -r docs/docs/html/* gh-pages/docs
        cd gh-pages/docs
        touch .nojekyll
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Update documentation via action" -a || true
        # The above command will fail if no changes were present, so we ignore
        # that.
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        branch: gh-pages
        directory: gh-pages
        github_token: ${{ secrets.GITHUB_TOKEN }}
